/*
 * NPS op RaadpleegIngeschrevenPersoonNAW
 *
 * Specificatie RSGB 3.0 Json opvragen NPS
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PersoonPeriodeGeldigheid : IEquatable<PersoonPeriodeGeldigheid>
    { 
        /// <summary>
        /// Gets or Sets Van
        /// </summary>
        [DataMember(Name="van")]
        public DateTime? Van { get; set; }

        /// <summary>
        /// Gets or Sets TotEnMet
        /// </summary>
        [DataMember(Name="totEnMet")]
        public DateTime? TotEnMet { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PersoonPeriodeGeldigheid {\n");
            sb.Append("  Van: ").Append(Van).Append("\n");
            sb.Append("  TotEnMet: ").Append(TotEnMet).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PersoonPeriodeGeldigheid)obj);
        }

        /// <summary>
        /// Returns true if PersoonPeriodeGeldigheid instances are equal
        /// </summary>
        /// <param name="other">Instance of PersoonPeriodeGeldigheid to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PersoonPeriodeGeldigheid other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Van == other.Van ||
                    Van != null &&
                    Van.Equals(other.Van)
                ) && 
                (
                    TotEnMet == other.TotEnMet ||
                    TotEnMet != null &&
                    TotEnMet.Equals(other.TotEnMet)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Van != null)
                    hashCode = hashCode * 59 + Van.GetHashCode();
                    if (TotEnMet != null)
                    hashCode = hashCode * 59 + TotEnMet.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PersoonPeriodeGeldigheid left, PersoonPeriodeGeldigheid right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PersoonPeriodeGeldigheid left, PersoonPeriodeGeldigheid right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
