version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image:  openapi-brp-fake
    build:
      context: ./openapi-brp-fake
      dockerfile: Dockerfile
    hostname: openapi-brp-fake
    restart: always
    logging: *default-logging