version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image:  openapi-brp-fake
    build:
      context: ./Org.OpenAPITools
      dockerfile: Dockerfile
    hostname: Org.OpenAPITools
    restart: always
    logging: *default-logging